### ISSUE TITLE
Put color scheme selector in tab bar(Or have it follow scroll)

### ISSUE THREAD

**Issue by CharlieS1103** [CharlieS1103/spicetify-marketplace#105]
Kind of annoying to have to scroll all the way back up to select color scheme(or it will be when we get more themes.)

**Comment by theRealPadster** [comment]
This is a good point. Probably not too difficult with some sticky or absolute positioning.

**Comment by theRealPadster** [comment]
It looks you need to make the whole container sticky, but then the header bar goes on top. We'd either have to account for that "Spicetify Marketplace" header item (add a background or something) or remove it. Or we could refactor the DOM for how the header bar and dropdown etc are laid out. 

![image](https://user-images.githubusercontent.com/1565883/150427216-7fc0ff1c-42b1-471b-b221-bbc70d0be92e.png)

**Comment by CharlieS1103** [comment]
We could move schemes to the user menu as well.

**Comment by theRealPadster** [comment]
> We could move schemes to the user menu as well.

I'd vote to avoid that. The specific colour scheme probably isn't something you're gonna change a ton, and the user menu can get kinda crowded already. Makes sense to keep it in the marketplace app somewhere I think.

**Comment by FlafyDev** [comment]
> It looks you need to make the whole container sticky, but then the header bar goes on top. We'd either have to account for that "Spicetify Marketplace" header item (add a background or something) or remove it. Or we could refactor the DOM for how the header bar and dropdown etc are laid out.


I'm not great with CSS but I managed to get the sticky effect without the h1 element by setting its position to fixed.
I had a problem aligning the h1 to where it was originally so I had to take the padding of the `.contentSpacing` element and put it in the h1's left property.

```css
.marketplace-header {
  position: sticky;
  top: 76px;
  z-index: 1;
  flex-direction: row-reverse;
}

.marketplace-header > h1 {
  position: fixed;
  left: 16px;
}

@media (min-width: 1024px) {
  .marketplace-header > h1 {
    left: 32px;
  }
}
```
